# Site settings
title: "<title>dev notes</title>"
email: your-email@domain.com
description: "Just a blog for my dev notes"
pygments: true
baseurl: "http://viktorsnt.github.io/dev-notes"
url: "http://viktorsnt.github.io/dev-notes"

# Build settings
markdown: kramdown
permalink: pretty
